[package]
name = "arkham"
version = "0.1.0"
edition = "2021"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "component_functions"
path = "examples/component_functions.rs"

[[example]]
name = "theme"
path = "examples/theme.rs"

[[example]]
name = "component_params"
path = "examples/component_params.rs"

[[example]]
name = "keyboard"
path = "examples/keyboard.rs"

[dependencies]
anyhow = "1.0.71"
crossterm = "0.26.1"
ctrlc = "3.3.1"
