name: Tests

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test base
        run: cargo test
      - name: test sync
        run: cargo test --features="sync"
